### ISSUE TITLE
zgesvx used but not in Rlapack

### ISSUE THREAD

**Issue by eddelbuettel** [plasmonics/cda#1]
We have a new interaction between cda, RcppArmadillo and R when using Rlapack.

You need the zgesvx symbol from LAPACK, we don't always have it.  See [here how RcppArmadillo checks](https://github.com/RcppCore/RcppArmadillo/blob/master/configure) for which LAPACK we have.  I fear that if you see Rlapack, you may have to copy in a file `zgesvx.f`. 

I do see your recent commit https://github.com/baptiste/cda/commit/539f71819ba33c1c3c3348bae379fc98f1dde346 removing zgels and I am sorry to be bearer of bad news but I fear we need to go this way.

**Comment by baptiste** [comment]
Hmm, I'll need to take another look at this when I get back in January. I'm rewriting the package from scratch anyway, so I will have a lot of changes to check before updating on CRAN. zgesvx, in contrast with zgels, is probably actually used for the inversion, so if I need to make a copy at least it will serve a purpose.
Thanks!

**Comment by eddelbuettel** [comment]
And thinking about this some, we can even be clever and _access the file at package build time_ only when needed.  As such, it won't even be part of your sources (in case you loath altering `DESCRIPTION` again, though CRAN is less finicky about that these days AFAICT).  We could fetch the fortran files from github and and when we need them -- Rblpapi does that for third-party headers and library too.

**Comment by eddelbuettel** [comment]
Conrad, awesome as he is, made a change upstream but promised 'no more after this'.  

I think we should probably take care of this at the level of your package(s) as needed and then bubble up into R's Rlapack as has happened with the earlier case.

**Comment by baptiste** [comment]
I'm a bit confused (admittedly, I was on holiday during this discussion):
- the CRAN version of cda shows not errors, and ships a copy of zgels, so why would [KH find it problematic](https://github.com/RcppCore/RcppArmadillo/issues/67)? 
- "Conrad made a change upstream" -- I could not find which change happened exactly: is it solving the issue with `zgesvx.f`, or just flagging it as unavailable on some systems? (I never actually see the problem unless I'm trying to submit on CRAN, since I develop on Mac or linux)
- assuming I need to do something, i.e. "take care of this at the level of your package", would that be simply adding the `zgesvx.f` file and updating the copyrights info, or do you have a preferred solution involving " access the file at package build time only when needed"? (I have no idea what the advantage would be)

Following your recent interaction with R-core regarding those 12 missing functions, hopefully these open issues will soon become irrelevant?

Thanks.

**Comment by eddelbuettel** [comment]
I am sorry but I have no time machine, relevant discussion happened mostly on or around Dec 10, it is now almost four weeks later -- and I had a lot of other reports on other packages in the meatime.

But in brief:
1. cda simply failed when used with Rlapack.so as the latter is missing twelve complex functions used by Armadillo.  
2. Conrad `#ifdef`'ed the use that was throwing cda off.  We already had a `#define` for a limited LAPACK in Rlapack, he uses it now in more places.
3. I don't know.  If you bundle it you can be assured it is there.
4. There was no interaction. There was me pleading with KH on Dec 10 (no answer) and following BDR's recent upgrade of the very LAPACK routines in Rlapack, a renewed plea to BDR + KH.  I have no idea if it ever amounts to something.

I am between a rock and a hard place.  Maybe I should just refuse to build RcppArmadillo when there is Rlapack in use.   On the other hand that would hurt thousands of Windows users most of when only use _real-valued_ data.  There are very few users of complex analysis like you.  But they get screwed.

**Comment by baptiste** [comment]
OK, thanks for the clarifications. It was quite hard for me to follow what had happened from reading your messages across those various threads.

**Comment by eddelbuettel** [comment]
I know, sorry about the multiple channels.  It's a bit of mess -- I bind R to Armadillo via RcppArmadillo and thus offer an rich-looking API but then _just sometimes_ pull the rug under people and say, no, sorry you can't have that.

Trouble is that it isn't me doing the rug-pulling.  So _someone_ actually has to sit down and insert the twelve functions I identified as missing.  Maybe that is R Core, maybe that is you (!!), maybe it is me (unlikely, I just don;t have complex-valued data) or maybe we all wait for Santa.  If R Core does not act, we _could_ try to insert them at the RcppArmadillo level.

**Comment by baptiste** [comment]
closed thanks to https://github.com/wch/r-source/commit/98acd96f22eb795a933879c0d3f740e802855473

**Comment by eddelbuettel** [comment]
Well but  R 3.3.0 won't be out for a while though...

**Comment by baptiste** [comment]
If I hear complaints from CRAN before then, I may try something (probably remove it from CRAN for the time being), but at the moment job search and immigration status have managed to get my attention with higher priority.

**Comment by eddelbuettel** [comment]
Agreed.  I'd say there is no change from your end:  under (what Conrad would call) "crippled" LAPACK cda will fail.  On a real computer with real LAPACK no issue.  So I'd just sit and wait.  Soon everybody (with R 3.3.0 or newer, once released) with have a full-featured LAPACK so all good there...
